### ISSUE TITLE
Shifthelper kept calling and sending me Telegram messages every 5 minutes and informed me about FlareAlert

### ISSUE THREAD

**Issue by lestrix** [fact-project/shifthelper#207] opened 2017-02-04 07:14 UTC
Although I "Acknowledged" it and answered the phone.  Problem persists even after shutdown.
-> killed shifter to stop spamming

**Comment by dneise** [comment] 2017-02-05 09:49
fixed in #211

**Comment by MaxNoe** [comment] 2017-02-06 11:45
Dupe of #198 and fixed with #211

**Closed by MaxNoe** 2017-02-06 11:45 UTC
