### ISSUE TITLE
Bad Gateway at log page.

### ISSUE THREAD

**Issue by mackaiver** [fact-project/shifthelper#236] opened 2017-05-17 20:08 UTC
When I go to https://shifthelper.app.tu-dortmund.de/log I get the following error:

![bildschirmfoto 2017-05-17 um 22 06 08](https://cloud.githubusercontent.com/assets/4076745/26173759/4b1b9e84-3b4d-11e7-9649-80586c34f0cf.png)

**Comment by dneise** [comment] 2017-05-17 20:29
Confirmed. Looks the same for me .... and I am nicely drunk ... :-D

**Comment by MaxNoe** [comment] 2017-05-17 21:15
MMh, this worked on the ihp-pc41 deployment, might have something to do with how this docker cloud works.

Will look into this.

**Comment by dneise** [comment] 2017-09-05 10:03
This was solved at some point, right? 
It was due to the local installation in dortmund right, and it did not need any changes in the shifthelper codebase right?

So Can I close this?

**Comment by MaxNoe** [comment] 2017-09-05 10:27
It was a wrong path in the config of the dortmund deployment

**Closed by MaxNoe** 2017-09-05 10:27 UTC
Labels: bug
